# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(266, 312)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_2.setObjectName("label_2")
        self.edit_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_ip.setGeometry(QtCore.QRect(10, 40, 125, 21))
        self.edit_ip.setObjectName("edit_ip")
        self.connect_test = QtWidgets.QPushButton(self.centralwidget)
        self.connect_test.setGeometry(QtCore.QRect(140, 30, 95, 31))
        self.connect_test.setObjectName("connect_test")
        self.date_start = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.date_start.setGeometry(QtCore.QRect(10, 110, 194, 22))
        self.date_start.setObjectName("date_start")
        self.date_end = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.date_end.setGeometry(QtCore.QRect(10, 180, 194, 22))
        self.date_end.setObjectName("date_end")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 131, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 131, 21))
        self.label_4.setObjectName("label_4")
        self.export_data = QtWidgets.QPushButton(self.centralwidget)
        self.export_data.setGeometry(QtCore.QRect(10, 220, 113, 32))
        self.export_data.setObjectName("export_data")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 266, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actiona = QtWidgets.QAction(MainWindow)
        self.actiona.setObjectName("actiona")
        self.actionb = QtWidgets.QAction(MainWindow)
        self.actionb.setObjectName("actionb")
        self.actiona_2 = QtWidgets.QAction(MainWindow)
        self.actiona_2.setObjectName("actiona_2")
        self.actionb_2 = QtWidgets.QAction(MainWindow)
        self.actionb_2.setObjectName("actionb_2")
        self.menu.addAction(self.actiona)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "简易数据导出工具"))
        self.label_2.setText(_translate("MainWindow", "需要导出的设备ip地址"))
        self.connect_test.setText(_translate("MainWindow", "连接测试"))
        self.label_3.setText(_translate("MainWindow", "开始时间"))
        self.label_4.setText(_translate("MainWindow", "结束时间"))
        self.export_data.setText(_translate("MainWindow", "点击导出数据"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.actiona.setText(_translate("MainWindow", "about"))
        self.actionb.setText(_translate("MainWindow", "b"))
        self.actiona_2.setText(_translate("MainWindow", "a"))
        self.actionb_2.setText(_translate("MainWindow", "b"))
